### ISSUE TITLE
Review #1 - Al no elegir jugada, el juego elije por vos.

### ISSUE THREAD

**Issue by FacundoEG** [RossiniMaximo/desafio-5#1]
Hola Maximo! primero que todo te felicito por terminar el desafío!

Sabes que estoy revisando la webapp, en general la veo funcionando muy bien, pero noto un detalle.

Cuando vos realizas una jugada (por ejemplo elegís piedra), la siguiente jugada si vos no realizas ningún movimiento vuelve a elegir la misma mano. Te pediría que revises eso, ya que sería mas conveniente que te redireccione hacia las instrucciones o que te avise que te quedaste sin tiempo. 

Tambíen se nota algo similar en la segunda vez que jugas, al no haber elegido ninguna mano te aparece la ultima jugada que hiciste, como si quedara guardada. 

![image](https://user-images.githubusercontent.com/79592789/135278613-22049cc4-d96a-4e5d-8c9e-431533d57fc9.png)

No es un gran error, pero puede prestar a un poco de confusión de parte del usuario.

La ultima cosa que te quiero comentar, es que si cierro la ventana y vuelvo a abrir el juego, el score se reinicia y vuelve a empezar desde cero, te recomendaría que revises si se estan guardando los resultados dentro del localstorage, quizas puede ser un error a la hora de que arranque el state e inicie el juego.

Sacando eso no note nada mas! son cosas super chiquitas, pero te tengo que pedir que lo revises si?

Esperamos esos cambios y dale que te falta muy poco!

Saludos!

PD: Muy lindo el cambio de diseño, la verdad que es un buen detalle.

**Comment by RossiniMaximo** [comment]
Buenas Facu , te agradezco por la revisión, si no me equivoco ya estarían
solucionados los problemitas que tenia. Recién hice deploy.Solo con build y
deploy esta bien ? O debería committear los cambios
tradicionalmente(haciendo add y commit)?

**Comment by FacundoEG** [comment]
Máximo por lo que tengo entendido primero va el build y después el deploy, ya que el deploy se realiza en base a la build.

Cuando tengas ya resuelto eso y subido con gh-pages avisame asi te cierro el issue si?

**Comment by RossiniMaximo** [comment]
Joya Facu ! Yo ya lo deployee , me parece que los cambios ya estan
realizados en la GitHub page

**Comment by FacundoEG** [comment]
Hola Maximo! recién ahora lo pude revisar para ver el tema de este issue y la verdad que no pude pasar de la pantalla de inicio en "/rules" `(https://rossinimaximo.github.io/rules)`

Me fije la consola y me llama la atención que el state te lo de en null

![image](https://user-images.githubusercontent.com/79592789/135522677-8d7809a7-c2b2-41c3-9fcb-9ac400eab8da.png)

Ya vi que arriba te hicieron un issue por esto, te sugeriría además de lo que te dijeron ya, que veas que sucede con el state al inicio, porque al parecer no puede leer las propiedades de un null y se rompe (puede pasar cuando esta leyendo `state.currentgame.playermove`, fíjate que al tocar el botón para pasar de pagina se repite este error).

También ser que haya algún tema con el localstorage y como inicia la app.

![image](https://user-images.githubusercontent.com/79592789/135523921-5d2a12dd-57bc-48c1-9222-41a869480ad5.png)


Cualquier cosita o duda que tengas avisa !

Saludos!

**Comment by RossiniMaximo** [comment]
Hola Facu como te va , si marcos me alerto de esto también , pero lo que no
entiendo es porque yo no puedo ver el error, al state null le habia dicho
que si no habia user-state en local data ejecute el estado de 0 , no
entiendoooooooooooooooooooooooooouuuuuuuuuuuuuuouououououuuuu

**Comment by RossiniMaximo** [comment]
Puede ser que no haya deployado bien o algo no se ?

**Comment by FacundoEG** [comment]
Y a mi me parece que si, ahora voy a bajar tu code y lo voy a probar en mi pc, pero si a vos se te ve bien y a nosotros no, o no se llego a hacer bien el deploy, o si no, como vos ya tenes guaradado un item dentro de localstorage con el state, al nosotros no tener ese ítem guardado en el localstorage puede ser que se rompa al querer abrirse y no estar. 

Ahora lo reviso, cualquier cosa si queres fíjate de hacer otro deploy a ver si en una de esas se arregla!

**Comment by FacundoEG** [comment]
Maximo mira, lo corrí desde mi compu bajando el código y me da el mismo error:

![image](https://user-images.githubusercontent.com/79592789/135540188-7d4cac31-c83f-43fc-8217-9519ffc6b817.png)

Creo que el problema podría estar en la función "init.storage", porque la borre y arranco el juego lo mas normal.

![image](https://user-images.githubusercontent.com/79592789/135540291-40316bdd-7256-476e-8ee5-b2f79c866cc8.png)

Fíjate que el if entra bien, pero state.data esta null y por ende lo guarda así en el localStorage:

![image](https://user-images.githubusercontent.com/79592789/135540327-a6490287-bfce-4cd8-919b-ea18a8f5dd22.png)

Podrías arreglarlo me parece, haciendo que si entra al if, tome lo que esta en ese momento en el state (aunque este vacío) y recíen ahi haga un set.item al localStorage con un user-state inicial asi no se rompe al arrancar.

**Comment by RossiniMaximo** [comment]
Hola Facu , primero muchas gracias por toda la revisión! , estuve hablando
con Marcos y  si , el también opina lo mismo , es mas, probo y lo soluciono
me parece, ahora estoy esperando un rato para ver si la página anda

**Comment by FacundoEG** [comment]
De nada Maximo! estamos para ayudarte

Ahora la pagina anda bien como antes, pero el tema es que noto que el score sigue sin "mantenerse"  una vez que cerras la pantalla y cuando no elegis ninguna acción la maquina juega directamente y terminas perdiendo, eso lo decidiste configurar vos así ?

**Comment by RossiniMaximo** [comment]
Hola Facu , si lo de que la maquina gane por defecto lo hice adrede ,
porque si el otro no juega nada cualquier cosa seria win condition ponele.
En cuanto a lo de el score , eso no estaba planeado asi que ahora mismo lo
verifico y te aviso que onda ,saludos

**Comment by FacundoEG** [comment]
Dale genial entonces, cierro el issue porque ya resolviste este tópico, tene en cuenta igual que estaría bueno avisarle al usuario que si no juega, la maquina va a elegir por su cuenta, como para que lo sepa.

Así que nada, te deseo suerte y nos vemos del otro lado!

Abrazo!

**Comment by RossiniMaximo** [comment]
Sisi estoy de acuerdo , no estaría de más para nada, ya hice el deploy por
el problema del localStorage y ya anda ,o capaz no  y la compu me esta
haciendo la triquiñuela. Lo que si es que la suma de scores se maneja de
una forma muy extraña , aveces se suma mucho
