### ISSUE TITLE
Review #2 - Error en botón jugar

### ISSUE THREAD

**Issue by Marcosreuquen** [RossiniMaximo/desafio-5#2]
Buenas, Máximo. 
No me dejó avanzar de la page rules. 
Al presionar el botón jugar me sale error de lectura del currentGame.
Te copio la captura: 
![image](https://user-images.githubusercontent.com/75027556/135384089-b0bda1d4-6f74-4b11-b19d-f7c7cb26bfbb.png)

Por lo que estuve chusmeando en el debugger, puede ser que estés pisando la clase contenedor al darle un nuevo innerHTML en la page:
![image](https://user-images.githubusercontent.com/75027556/135384211-b2d7afe7-01c4-4609-8673-bb842b36b9d5.png)

Saludos!

**Comment by RossiniMaximo** [comment]
Buenas Marcos , puede ser que haya sido una casualidad ?. Porque ami me
anda bien cuando juego
