### ISSUE TITLE
Review #3 - LocalStorage del history

### ISSUE THREAD

**Issue by Marcosreuquen** [RossiniMaximo/desafio-5#3]
Buenas, Máximo. 
Ante todo, creo que quedó muy bien y me encantó como personalizaste el juego. 
Hay dos detalles que estaría bueno verlos. El history queda vacío en el localStorage al salir de la web y el conteo del juego queda dentro del objeto user-data pero no guarda el dato del puntaje. Habría que agregarle el history para que cuando vuelvas siga tomando el puntaje en el que quedaste. 

![image](https://user-images.githubusercontent.com/75027556/135765201-a1d578ff-3313-47ba-b008-34056aec63f8.png)
![image](https://user-images.githubusercontent.com/75027556/135765210-2c1b843a-6fca-4764-968d-9c0ae3d323b5.png)

El otro tema es que cuando uno no elije ninguna mano y pasa el tiempo, el juego sigue dandote por perdida la partida, capaz ahí podrías decirle que si aún no eligió jugada y pasó el tiempo, que vuelva a la page de rules. 

![image](https://user-images.githubusercontent.com/75027556/135765305-fe443ccf-ec45-4d17-93c5-53f0c0e43e68.png)
![image](https://user-images.githubusercontent.com/75027556/135765310-b8bd53cf-cf74-409a-9405-c35c780d58b4.png)

Y sobre lo que me contabas que caía en recursividad cuando dabas click, me parece que es por los listeners. Creo que estás suscribiendo desde el componente de las manos y eso hace que se suscriba al state cada vez que el DOM agrega una mano en la page. Capaz, para evitarlo, podrías suscribir desde la page. 

![image](https://user-images.githubusercontent.com/75027556/135765276-a6534157-3054-4895-a6b4-64f58229bc63.png)

Saludos!

**Comment by RossiniMaximo** [comment]
Buenas Marcos, como va , gracias por la revisión y consejos! Ahi deployee
los cambios para que la página persista. Me confirmarias si anda el
localStorage ya ?

**Comment by RossiniMaximo** [comment]
Además ahi probe sacandole el suscribe que me habias dicho y no entra mas
en recursivadad parece!!

**Comment by RossiniMaximo** [comment]
Estoy chequeando en incognito pero no , no anda, no entiendo porque no me entra if de si da null la localdata

**Comment by Marcosreuquen** [comment]
Me parece que buscás local-data pero lo guardás en user-data.

**Comment by RossiniMaximo** [comment]
Claro localdata le puse a la constante que busca el user-data

**Comment by Marcosreuquen** [comment]
Hey, ya funca. Acabo de probar y funca 10 puntos el local storage. Ciero este issue nomás! **Felicitaciones de nuevo!**

**Comment by RossiniMaximo** [comment]
Gracias Marcos , pero no se si anda 100% , es como que anda si primero
entras intentas jugar no te deja  y desp abris la pág denuevo y anda de una
, pareciera como que primero tiene que setear el localStorage , pero no
puede setearlo de una y largar el juego de una ?
