### ISSUE TITLE
Review #4 - El div que contiene los resultados se corre a la izquierda en modo mobile.

### ISSUE THREAD

**Issue by FacundoEG** [RossiniMaximo/desafio-5#4]
Hola Maximo! además de lo que te remarco Marcos en la review #3, me gustaría agregar que noto un pequeño error de diseño en el div que contiene los scores al final de la partida, fíjate que se corre a la izquierda en modo mobile:

![image](https://user-images.githubusercontent.com/79592789/135778738-35dd5f29-ec0c-4653-a149-5cefd91d1e4d.png)

Sacando eso, no noté nada mas (además de lo que ya te sugirieron en la review anterior) así que solamente te dejo ese pequeño detalle para que veas.

Saludos y dale que va quedando el desafío!

**Comment by RossiniMaximo** [comment]
Dale Facu , gracias x avisar !

**Comment by RossiniMaximo** [comment]
Ya lo "solucione"  , quedo mejor para mi gusto

**Comment by FacundoEG** [comment]
Dale Maximo! ahi lo revise y entre los 550px y los 958px sigue corriéndose a la izquierda, pero es una resolución mas de Tablet que otra cosa, te cierro el issue porque era mas que nada informativo.

Te mando saludos y suerte con esa aprobada!

**Comment by RossiniMaximo** [comment]
Muchas gracias Facu!
